name: maize_gxe_prediction
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python environment
  - python=3.8
  - pip
  - setuptools
  - wheel
  
  # Scientific computing stack
  - numpy>=1.20
  - pandas>=1.3
  - scipy>=1.7
  - scikit-learn>=1.0
  
  # Plotting and visualization  
  - matplotlib>=3.2
  - seaborn>=0.11
  
  # Data handling
  - pyarrow>=10.0
  
  # Statistics and modeling
  - statsmodels>=0.13
  - patsy
  
  # Development tools (optional)
  - ipython
  - jupyter_core
  - ipykernel
  
  # Utilities
  - tabulate
  - requests
  - pyyaml
  
  # pip dependencies
  - pip:
    - lightgbm>=3.3.0
    - optuna>=3.0.0
    - joblib>=1.2.0
    - tqdm>=4.60.0
    - alembic>=1.9.0
    - cmaes>=0.9.0
    - colorlog>=6.7.0
    - greenlet>=2.0.0
    - mako>=1.2.0
    - markupsafe>=2.1.0
    - packaging>=23.0
    - pytz>=2022.7.0
    - sqlalchemy>=2.0.0
    - threadpoolctl>=3.1.0
    - typing-extensions>=4.5.0